### ISSUE TITLE
DateTimeUtils ขอแบบ custom DateFormater ได้หน่อย

### ISSUE THREAD

**Issue by f1uke** [WisanuPljk19/necromancer#1]
DateTimeUtils พวก toDate, toString ขอแบบ custom DateFormater ได้หน่อย
วันนี้เจองานที่มี format แปลกๆแล้วต้องมา custom เอง ลำบาก!

**Comment by ghost** [comment]
done

**Comment by wisanu-dev** [comment]
done

**Comment by f1uke** [comment]
❤
